# Generated by Django 5.2.7 on 2025-10-21 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_initial'),
    ]

    operations = [
    ]
