# Generated by Django 5.2.7 on 2025-10-21 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_auto_20251021_2130'),
    ]

    operations = [
    ]
