# Generated by Django 5.2.7 on 2025-10-21 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_auto_20251021_2137'),
    ]

    operations = [
    ]
